### ISSUE TITLE
Cierre inesperado - Branch refactor/graphics

### ISSUE THREAD

**Issue by Derillo** [ao-libre/ao-java#116]
```
Exception in thread "main" java.lang.NullPointerException
        at game.systems.render.world.CharacterRenderingSystem.getMovementOffset(CharacterRenderingSystem.java:46)
        at game.systems.render.world.CharacterRenderingSystem.access$100(CharacterRenderingSystem.java:34)
        at game.systems.render.world.CharacterRenderingSystem$CharacterDrawer.getMovementOffsetY(CharacterRenderingSystem.java:172)
        at game.systems.render.world.CharacterRenderingSystem$CharacterDrawer.calculateOffsets(CharacterRenderingSystem.java:143)
        at game.systems.render.world.CharacterRenderingSystem$CharacterDrawer.<init>(CharacterRenderingSystem.java:88)
        at game.systems.render.world.CharacterRenderingSystem$CharacterDrawer.createDrawer(CharacterRenderingSystem.java:92)
        at game.systems.render.world.CharacterRenderingSystem.drawPlayer(CharacterRenderingSystem.java:63)
        at game.systems.render.world.WorldRenderingSystem.lambda$null$2(WorldRenderingSystem.java:73)
        at java.util.Optional.ifPresent(Optional.java:159)
        at game.systems.render.world.WorldRenderingSystem.lambda$processSystem$4(WorldRenderingSystem.java:73)
        at game.systems.render.world.WorldRenderingSystem$UserRange.forEachTile(WorldRenderingSystem.java:156)
        at game.systems.render.world.WorldRenderingSystem.processSystem(WorldRenderingSystem.java:69)
        at com.artemis.BaseSystem.process(BaseSystem.java:46)
        at com.artemis.InvocationStrategy.process(InvocationStrategy.java:25)
        at com.artemis.World.process(World.java:385)
        at game.screens.GameScreen.update(GameScreen.java:158)
        at game.screens.GameScreen.render(GameScreen.java:184)
        at game.screens.transitions.FadingGame.render(FadingGame.java:78)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at launcher.DesktopLauncher.main(DesktopLauncher.java:66)

```

**Comment by Derillo** [comment]
No se volvió a repetir el error luego de las optimizaciones en el branch.
