### ISSUE TITLE
Server unregisters non-existent entity

### ISSUE THREAD

**Issue by cpbeto** [ao-libre/ao-java#150]
Server tries to unregister an entity that does not exist in the client.
```java
// WorldManager.java
public void unregisterEntity(int networkId) {
    try {
        int entityId = networkedEntities.get(networkId);
        world.delete(entityId);
        networkedEntities.remove(networkId);
    }
    catch(Exception e) {
        Log.error("unregisterEntity(" + networkId + ")", e);
    }
}
```
```
00:16 ERROR: unregisterEntity(2858)
java.lang.NullPointerException
	at game.managers.WorldManager.unregisterEntity(WorldManager.java:37)
	at game.network.GameNotificationProcessor.processNotification(GameNotificationProcessor.java:84)
	at shared.network.notifications.RemoveEntity.accept(RemoveEntity.java:19)
	at game.systems.network.ClientSystem.lambda$received$0(ClientSystem.java:33)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:153)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at launcher.DesktopLauncher.main(DesktopLauncher.java:63)
```

**Comment by cpbeto** [comment]
![image](https://user-images.githubusercontent.com/41555339/61920020-6f2bab00-af2e-11e9-84a6-1090e4add0d8.png)

**Comment by jopiortiz** [comment]
Fixed
