### ISSUE TITLE
Crashea Al seleccionar Ciertos NPCs en la lista

### ISSUE THREAD

**Issue by Derillo** [ao-libre/ao-java#163]
`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 2139 out of bounds for length 514
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at game.handlers.DescriptorHandler.getHead(DescriptorHandler.java:51)
	at game.handlers.AnimationHandler.lambda$getHeadAnimation$0(AnimationHandler.java:83)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at game.handlers.AnimationHandler.getHeadAnimation(AnimationHandler.java:82)
	at game.systems.render.world.CharacterRenderingSystem$CharacterDrawer.drawHead(CharacterRenderingSystem.java:172)
	at game.systems.render.world.CharacterRenderingSystem$CharacterDrawer.draw(CharacterRenderingSystem.java:124)
	at design.screens.views.NPCView$AnimationActor.draw(NPCView.java:204)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Container.draw(Container.java:61)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.draw(Button.java:257)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:96)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:598)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.draw(SplitPane.java:260)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.draw(SplitPane.java:269)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at design.screens.DesignScreen.render(DesignScreen.java:65)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at launcher.DesignCenter.render(DesignCenter.java:67)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at launcher.DesignCenterLauncher.main(DesignCenterLauncher.java:17)`

**Comment by Derillo** [comment]
Se produce otro error al listar npcs, para reproducirlo seleccionar el npc 190:
`Exception in thread "main" java.lang.NullPointerException
	at design.screens.views.NPCView$AnimationActor.act(NPCView.java:190)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.act(ScrollPane.java:277)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:222)
	at design.screens.DesignScreen.render(DesignScreen.java:64)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at launcher.DesignCenter.render(DesignCenter.java:67)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at launcher.DesignCenterLauncher.main(DesignCenterLauncher.java:17)`
