### ISSUE TITLE
No carga el proyecto

### ISSUE THREAD

**Issue by Derillo** [ao-libre/ao-java#175]
Al intentar iniciar el proyecto, surge el error en al línea
        **assetManager.load();**

```
Exception in thread "main" java.lang.NullPointerException
	at launcher.DesignCenter.create(DesignCenter.java:49)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at launcher.DesignCenterLauncher.main(DesignCenterLauncher.java:19)

Process finished with exit code 1
```

**Comment by jopiortiz** [comment]
Fixed.
